# Generated by Django 3.2.3 on 2021-11-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_athleticbelts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthleticBelts',
            new_name='AthleticBelt',
        ),
    ]
