# Generated by Django 3.2.3 on 2021-11-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
