# Generated by Django 3.2.3 on 2021-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerliftingbelt',
            name='width',
            field=models.CharField(default=' ', max_length=255, verbose_name='Ширина пояса'),
            preserve_default=False,
        ),
    ]
